### ISSUE TITLE
브라우저의 Event Loop

### ISSUE THREAD

**Issue by gowoonsori** [Nelmm/review-techo-talk#1]
유튜브 링크 : https://www.youtube.com/watch?v=YpQTeIqjC4o

**Comment by gowoonsori** [comment]
## 메인 스레드
브라우저에서 Renerer Process 내에 main thread / worker thread / compositor thread / raster thread ... 여러 스레드로 동작한다.
우리가 흔히 `JS는 싱글스레드` 라고 하는 것은 `main thread`를 지칭. 이 메인스레드는 renedering과 js code를 처리하는 일을 모두 수행.

이때 타이머나 네트워크 통신과 같은 부분은 메인스레드에서 이루어지는 것이 아니라 브라우저 안에 있는 다른 프로세스나 스레드에서 실행하고 끝났을때 TaskQueue에 넣어주는 방식으로 동작.

## Queue 종류
### 1. MacroTaskQueue(Task Queue라고도 함)
- setTimeout(), setInterval(), event dispatch, network response 와 같은 메서드 사용시 해당 큐 사용
- 큐에서 Task를 하나씩 처리

### 2. MicroTaskQueue
- Promise, async/await, process.nextTick, Object.observe, MutationObserver 같은 비동기 호출 사용 시 해당 큐 사용
- 해당 큐가 빌 때까지 task를 계속 처리
- 다른 큐들에 비해 Task 처리 우선순위 1위

### 3. AnimationFrameQueue
- requestAnimationFrame 으로 등록한 callback 들이 해당 큐 사용
- repaint 직전에 큐에있는 task 모두 처리
- MicroTaskQueue보다는 우선순위가 낮고 MacroTaskQueue보다는 우선순위가 높다.

**Comment by dev-splin** [comment]
아래 링크의 블로그에 이미지로 동작에 대한 순서에 맞춰 설명이 잘 되어 있어서 한 번 참고하면 좋을 것 같습니다!
특히, async, await의 동작 방법이 약간 다른 것이 인상적이었습니다.
- [[JavaScript] Task Queue말고 다른 큐가 더 있다고? (MicroTask Queue, Animation Frames)](https://velog.io/@titu/JavaScript-Task-Queue%EB%A7%90%EA%B3%A0-%EB%8B%A4%EB%A5%B8-%ED%81%90%EA%B0%80-%EB%8D%94-%EC%9E%88%EB%8B%A4%EA%B3%A0-MicroTask-Queue-Animation-Frames-Render-Queue)
